### ISSUE TITLE
Add Types 

### ISSUE THREAD

**Issue by Abg4real** [AmeyaJain-25/Awesome-React-Stepper#2]
Hi @AmeyaJain-25 
The component looks quite solid and there are a whole lot of features you can add to it.
I feel, first and foremost, you should add types to the project. They are incredibly useful while writing and debugging, and they will certainly be needed as various people use react with typescript.
You can either switch from JS to TS for the whole project (I believe this will be easier as the project is in the initial stage) or you can add types via DefinitelyTyped.

You can refer to [this typescript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
I can help with this.

**Comment by AmeyaJain-25** [comment]
Yeah @Abg4real, was gonna add those types to the `Stepper`. But due to release, didn't kept as a primary change.
Let's add the types for this package as the crowd is more on typescript side.

**Comment by axydavid** [comment]
Awesome initiative, no TypeScript support :(

**Comment by AmeyaJain-25** [comment]
@axydavid It will be soon out with the updated version of typescript supportive 🚀
